name: ci-build

on:
  workflow_call:

jobs:
  ci-build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx256M"

    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2

    - name: Install JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build and Run unit tests
      run: mvn clean install -DskipIntTests -DskipDeploy --batch-mode
